// Centralized mapping from Lucide icon names to Material Symbols Rounded
// Bold, filled, modern aesthetic — inspired by iOS 18 / Instagram / Figma
export const ICON_MAP: Record<string, string> = {
  // Navigation & Layout
  LayoutDashboard: 'dashboard',
  Menu: 'menu',
  X: 'close',
  ChevronRight: 'chevron_right',
  ChevronDown: 'expand_more',
  ChevronUp: 'expand_less',
  ChevronLeft: 'chevron_left',
  ArrowLeft: 'arrow_back_ios_new',
  ArrowRight: 'arrow_forward_ios',
  ArrowUpRight: 'north_east',
  ExternalLink: 'open_in_new',
  Home: 'cottage',
  MoreHorizontal: 'more_horiz',
  MoreVertical: 'more_vert',
  LayoutList: 'view_agenda',
  LayoutGrid: 'grid_view',

  // Actions
  Plus: 'add_circle',
  Minus: 'do_not_disturb_on',
  Pencil: 'ink_pen',
  Trash2: 'delete_forever',
  Save: 'bookmark_added',
  Copy: 'content_copy',
  Search: 'travel_explore',
  Filter: 'filter_alt',
  Sort: 'swap_vert',
  RefreshCw: 'autorenew',
  Download: 'cloud_download',
  Upload: 'cloud_upload',
  Send: 'near_me',
  Link2: 'add_link',
  Archive: 'inventory',

  // Status & Feedback
  Check: 'task_alt',
  CheckCircle2: 'verified',
  AlertTriangle: 'crisis_alert',
  AlertCircle: 'report',
  XCircle: 'block',
  Info: 'help',
  Eye: 'preview',
  EyeOff: 'visibility_off',

  // Business & Finance
  DollarSign: 'universal_currency_alt',
  Wallet: 'account_balance_wallet',
  Landmark: 'assured_workload',
  CreditCard: 'credit_card',
  Receipt: 'receipt',
  ArrowUpCircle: 'arrow_circle_up',
  ArrowDownCircle: 'arrow_circle_down',
  ArrowLeftRight: 'swap_horiz',
  ArrowRightLeft: 'swap_horiz',
  TrendingUp: 'trending_up',
  TrendingDown: 'trending_down',
  PieChart: 'donut_large',
  Percent: 'percent',
  Coins: 'toll',
  ShoppingCart: 'shopping_cart',
  ShoppingBag: 'shopping_bag',
  ShoppingBasket: 'shopping_basket',

  // People & Communication
  User: 'account_circle',
  UserPlus: 'person_add',
  Users: 'groups',
  UserSearch: 'person_search',
  UserCheck: 'how_to_reg',
  MessageCircle: 'chat_bubble',
  MessageSquare: 'sms',
  Mail: 'forward_to_inbox',
  Bell: 'notifications_active',
  BellRing: 'ring_volume',
  Phone: 'call',
  Send2: 'near_me',

  // Organization
  Package: 'package_2',
  PackageX: 'deployed_code_alert',
  PackageCheck: 'deployed_code',
  ClipboardCheck: 'order_approve',
  ClipboardList: 'fact_check',
  Folder: 'folder_open',
  FileText: 'draft',
  StickyNote: 'sticky_note_2',
  ListChecks: 'checklist_rtl',

  // Settings & System
  Settings: 'manufacturing',
  Settings2: 'instant_mix',
  Shield: 'admin_panel_settings',
  Lock: 'encrypted',
  LogOut: 'move_item',
  Building2: 'domain',
  Monitor: 'desktop_mac',
  Globe: 'language',
  Hash: 'tag',
  Scale: 'balance',

  // Content & Media
  Image: 'photo_library',
  Camera: 'photo_camera',
  BookOpen: 'menu_book',
  Lightbulb: 'emoji_objects',
  Sparkles: 'magic_exchange',
  Brain: 'cognition',

  // Time & Calendar
  CalendarDays: 'date_range',
  Calendar: 'event',
  Clock: 'avg_pace',
  History: 'manage_history',

  // Food & Industry
  ChefHat: 'skillet',
  Utensils: 'restaurant',
  Soup: 'ramen_dining',
  UtensilsCrossed: 'flatware',

  // Rewards & Achievements
  Gift: 'featured_seasonal_and_gifts',
  Star: 'kid_star',
  Trophy: 'trophy',
  Crown: 'crown',
  Gem: 'diamond',
  Medal: 'rewarded_ads',
  Award: 'social_leaderboard',
  PartyPopper: 'celebration',
  FlaskConical: 'experiment',
  Calculator: 'calculate',

  // Misc
  Sun: 'light_mode',
  Moon: 'bedtime',
  QrCode: 'qr_code_scanner',
  Megaphone: 'campaign',
  Target: 'adjust',
  Grip: 'drag_indicator',
  GripVertical: 'drag_indicator',

  // Transport & Vehicles
  Car: 'directions_car',
  Truck: 'local_shipping',
  Bus: 'directions_bus',
  Fuel: 'local_gas_station',
  Plane: 'flight',

  // Finance categories (common)
  Banknote: 'local_atm',
  BadgeDollarSign: 'paid',
  PiggyBank: 'savings',
  HandCoins: 'volunteer_activism',
  CircleDollarSign: 'monetization_on',
  BarChart3: 'equalizer',
  BarChart: 'equalizer',
  LineChart: 'show_chart',
  Activity: 'vital_signs',
  Repeat: 'laps',
  FileSignature: 'contract_edit',

  // Building & Places
  Briefcase: 'business_center',
  Building: 'corporate_fare',
  Store: 'storefront',
  Hospital: 'local_hospital',
  GraduationCap: 'school',

  // Home & Living
  House: 'cottage',
  Sofa: 'weekend',
  Droplets: 'water_drop',
  Zap: 'bolt',
  Wifi: 'wifi',
  Wrench: 'construction',
  Hammer: 'handyman',
  Paintbrush: 'palette',
  Scissors: 'content_cut',

  // Health & Body
  Heart: 'cardiology',
  HeartPulse: 'ecg_heart',
  Pill: 'medication',
  Stethoscope: 'stethoscope',
  Dumbbell: 'exercise',

  // Entertainment
  Music: 'music_note',
  Film: 'movie',
  Gamepad2: 'sports_esports',
  Dices: 'casino',
  Ticket: 'confirmation_number',
  Coffee: 'local_cafe',
  Wine: 'wine_bar',
  Beer: 'sports_bar',
  Pizza: 'local_pizza',
  Apple: 'nutrition',

  // Tech
  Smartphone: 'smartphone',
  Shirt: 'checkroom',
  Flame: 'whatshot',
  Laptop: 'laptop_mac',
  Tv: 'connected_tv',
  Headphones: 'headphones',
  Printer: 'print',

  // Nature
  TreePine: 'park',
  Flower2: 'local_florist',
  Dog: 'pets',
  Cat: 'pets',
  Leaf: 'eco',

  // Documents
  FileCheck: 'task',
  FilePlus: 'note_add',
  Files: 'file_copy',
  Paperclip: 'attach_file',
  Bookmark: 'collections_bookmark',
  Tag: 'new_label',
  Tags: 'sell',

  // Additional
  Bot: 'robot_2',
  Vault: 'enhanced_encryption',
  CircleAlert: 'report',
  CalendarRange: 'date_range',
  CalendarIcon2: 'event',
  Bath: 'bathtub',
  WifiOff: 'wifi_off',
  ToggleLeft: 'toggle_off',
  ToggleRight: 'toggle_on',
  Edit2: 'ink_pen',
  PenLine: 'edit_note',
  FileImage: 'photo_library',
  ImageIcon: 'photo_library',
  Play: 'play_circle',
  Pause: 'pause_circle',
  Power: 'power_rounded',
  Loader2: 'progress_activity',
  Delete: 'backspace',
};
