// Centralized mapping from Lucide icon names to Material Symbols Rounded
// Modern, Instagram-inspired icon set — clean, rounded, filled aesthetic
export const ICON_MAP: Record<string, string> = {
  // Navigation & Layout
  LayoutDashboard: 'dashboard',
  Menu: 'menu',
  X: 'close',
  ChevronRight: 'chevron_right',
  ChevronDown: 'expand_more',
  ChevronUp: 'expand_less',
  ChevronLeft: 'chevron_left',
  ArrowLeft: 'arrow_back_ios_new',
  ArrowRight: 'arrow_forward_ios',
  ArrowUpRight: 'north_east',
  ExternalLink: 'open_in_new',
  Home: 'cottage',
  MoreHorizontal: 'more_horiz',
  MoreVertical: 'more_vert',
  LayoutList: 'view_agenda',
  LayoutGrid: 'grid_view',

  // Actions
  Plus: 'add',
  Minus: 'remove',
  Pencil: 'ink_pen',
  Trash2: 'delete',
  Save: 'save',
  Copy: 'content_copy',
  Search: 'manage_search',
  Filter: 'tune',
  Sort: 'swap_vert',
  RefreshCw: 'sync',
  Download: 'download',
  Upload: 'upload',
  Send: 'near_me',
  Link2: 'link',
  Archive: 'archive',

  // Status & Feedback
  Check: 'check',
  CheckCircle2: 'check_circle',
  AlertTriangle: 'warning',
  AlertCircle: 'error',
  XCircle: 'cancel',
  Info: 'info',
  Eye: 'preview',
  EyeOff: 'visibility_off',

  // Business & Finance
  DollarSign: 'universal_currency_alt',
  Wallet: 'account_balance_wallet',
  Landmark: 'account_balance',
  CreditCard: 'credit_card',
  Receipt: 'receipt',
  ArrowUpCircle: 'arrow_circle_up',
  ArrowDownCircle: 'arrow_circle_down',
  ArrowLeftRight: 'swap_horiz',
  ArrowRightLeft: 'swap_horiz',
  TrendingUp: 'trending_up',
  TrendingDown: 'trending_down',
  PieChart: 'donut_large',
  Percent: 'percent',
  Coins: 'monetization_on',
  ShoppingCart: 'shopping_cart',
  ShoppingBag: 'shopping_bag',
  ShoppingBasket: 'shopping_basket',

  // People & Communication
  User: 'face',
  UserPlus: 'person_add',
  Users: 'groups',
  UserSearch: 'contacts',
  UserCheck: 'how_to_reg',
  MessageCircle: 'chat_bubble',
  MessageSquare: 'forum',
  Mail: 'mail',
  Bell: 'notifications_unread',
  BellRing: 'notifications_active',
  Phone: 'call',
  Send2: 'send',

  // Organization
  Package: 'package_2',
  PackageX: 'inventory',
  PackageCheck: 'fact_check',
  ClipboardCheck: 'order_approve',
  ClipboardList: 'checklist',
  Folder: 'folder',
  FileText: 'article',
  StickyNote: 'sticky_note_2',
  ListChecks: 'checklist',

  // Settings & System
  Settings: 'manufacturing',
  Settings2: 'tune',
  Shield: 'admin_panel_settings',
  Lock: 'lock',
  LogOut: 'logout',
  Building2: 'apartment',
  Monitor: 'desktop_mac',
  Globe: 'public',
  Hash: 'tag',
  Scale: 'balance',

  // Content & Media
  Image: 'image',
  Camera: 'photo_camera',
  BookOpen: 'menu_book',
  Lightbulb: 'emoji_objects',
  Sparkles: 'magic_exchange',
  Brain: 'cognition',

  // Time & Calendar
  CalendarDays: 'date_range',
  Calendar: 'calendar_today',
  Clock: 'schedule',
  History: 'history',

  // Food & Industry
  ChefHat: 'skillet',
  Utensils: 'restaurant',
  Soup: 'ramen_dining',
  UtensilsCrossed: 'restaurant',

  // Rewards & Achievements
  Gift: 'featured_seasonal_and_gifts',
  Star: 'grade',
  Trophy: 'trophy',
  Crown: 'crown',
  Gem: 'diamond',
  Medal: 'rewarded_ads',
  Award: 'social_leaderboard',
  PartyPopper: 'celebration',
  FlaskConical: 'science',
  Calculator: 'calculate',

  // Misc
  Sun: 'light_mode',
  Moon: 'dark_mode',
  QrCode: 'qr_code_scanner',
  Megaphone: 'breaking_news',
  Target: 'my_location',
  Grip: 'drag_indicator',
  GripVertical: 'drag_indicator',

  // Transport & Vehicles
  Car: 'directions_car',
  Truck: 'local_shipping',
  Bus: 'directions_bus',
  Fuel: 'local_gas_station',
  Plane: 'flight',

  // Finance categories (common)
  Banknote: 'payments',
  BadgeDollarSign: 'paid',
  PiggyBank: 'savings',
  HandCoins: 'toll',
  CircleDollarSign: 'monetization_on',
  BarChart3: 'bar_chart',
  BarChart: 'bar_chart',
  LineChart: 'show_chart',
  Activity: 'monitoring',
  Repeat: 'repeat',
  FileSignature: 'contract_edit',

  // Building & Places
  Briefcase: 'work',
  Building: 'business',
  Store: 'storefront',
  Hospital: 'local_hospital',
  GraduationCap: 'school',

  // Home & Living
  House: 'home',
  Sofa: 'weekend',
  Droplets: 'water_drop',
  Zap: 'bolt',
  Wifi: 'wifi',
  Wrench: 'build',
  Hammer: 'handyman',
  Paintbrush: 'brush',
  Scissors: 'content_cut',

  // Health & Body
  Heart: 'cardiology',
  HeartPulse: 'monitor_heart',
  Pill: 'medication',
  Stethoscope: 'stethoscope',
  Dumbbell: 'fitness_center',

  // Entertainment
  Music: 'music_note',
  Film: 'movie',
  Gamepad2: 'stadia_controller',
  Dices: 'casino',
  Ticket: 'confirmation_number',
  Coffee: 'local_cafe',
  Wine: 'wine_bar',
  Beer: 'sports_bar',
  Pizza: 'local_pizza',
  Apple: 'nutrition',

  // Tech
  Smartphone: 'smartphone',
  Shirt: 'checkroom',
  Flame: 'whatshot',
  Laptop: 'laptop_mac',
  Tv: 'tv',
  Headphones: 'headphones',
  Printer: 'print',

  // Nature
  TreePine: 'park',
  Flower2: 'local_florist',
  Dog: 'pets',
  Cat: 'pets',
  Leaf: 'eco',

  // Documents
  FileCheck: 'task',
  FilePlus: 'note_add',
  Files: 'file_copy',
  Paperclip: 'attach_file',
  Bookmark: 'bookmark',
  Tag: 'label',
  Tags: 'sell',

  // Additional
  Bot: 'robot_2',
  Vault: 'lock',
  CircleAlert: 'error',
  CalendarRange: 'date_range',
  CalendarIcon2: 'calendar_today',
  Bath: 'bathtub',
  WifiOff: 'wifi_off',
  ToggleLeft: 'toggle_off',
  ToggleRight: 'toggle_on',
  Edit2: 'edit',
  PenLine: 'edit_note',
  FileImage: 'image',
  ImageIcon: 'image',
  Play: 'play_arrow',
  Pause: 'pause',
  Power: 'power_settings_new',
  Loader2: 'progress_activity',
  Delete: 'backspace',
};