import {
  SquaresFour,
  List,
  X,
  CaretRight,
  CaretDown,
  CaretUp,
  CaretLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowSquareOut,
  House,
  DotsThreeOutline,
  DotsThreeOutlineVertical,
  Rows,
  GridFour,
  BookOpen,
  ForkKnife,
  Plus,
  Minus,
  PencilSimple,
  Trash,
  FloppyDisk,
  Copy,
  MagnifyingGlass,
  Funnel,
  ArrowsDownUp,
  ArrowsClockwise,
  DownloadSimple,
  UploadSimple,
  PaperPlaneTilt,
  LinkSimple,
  Archive,
  Check,
  CheckCircle,
  Warning,
  WarningCircle,
  XCircle,
  Info,
  Eye,
  EyeSlash,
  CurrencyDollar,
  Wallet,
  Bank,
  CreditCard,
  Receipt,
  ArrowCircleUp,
  ArrowCircleDown,
  ArrowsLeftRight,
  TrendUp,
  TrendDown,
  ChartPie,
  Percent,
  Coins,
  ShoppingCart,
  ShoppingBag,
  Basket,
  User,
  UserPlus,
  Users,
  Handshake,
  UserList,
  UserCheck,
  ChatCircle,
  ChatTeardropDots,
  Envelope,
  Bell,
  BellRinging,
  Phone,
  Package,
  Clipboard,
  ClipboardText,
  ListChecks,
  Folder,
  FileText,
  Note,
  Gear,
  SlidersHorizontal,
  Shield,
  Lock,
  LockOpen,
  SignOut,
  Buildings,
  Monitor,
  Globe,
  Hash,
  Scales,
  ImageSquare,
  Camera,
  BookOpenText,
  Lightbulb,
  Sparkle,
  Brain,
  CalendarBlank,
  CalendarDots,
  Clock,
  ClockCounterClockwise,
  CookingPot,
  Gift,
  Star,
  Trophy,
  Crown,
  Diamond,
  Medal,
  Certificate,
  Confetti,
  Flask,
  Calculator,
  Sun,
  Moon,
  QrCode,
  Megaphone,
  Crosshair,
  DotsSixVertical,
  Car,
  Truck,
  Bus,
  GasPump,
  AirplaneTilt,
  Money,
  CurrencyCircleDollar,
  PiggyBank,
  ChartBar,
  ChartLine,
  Pulse,
  Repeat,
  Signature,
  Briefcase,
  Building,
  Storefront,
  FirstAidKit,
  GraduationCap,
  Armchair,
  Drop,
  Lightning,
  WifiHigh,
  Wrench,
  Hammer,
  PaintBrush,
  Scissors,
  Heart,
  Heartbeat,
  Pill,
  Stethoscope,
  Barbell,
  MusicNote,
  FilmSlate,
  GameController,
  DiceFive,
  Ticket,
  Coffee,
  Wine,
  BeerStein,
  Pizza,
  FruitApple,
  Bread,
  Hamburger,
  Leaf,
  Egg,
  SprayBottle,
  DeviceMobile,
  TShirt,
  Fire,
  Laptop,
  Television,
  Headphones,
  Printer,
  Tree,
  Flower,
  PawPrint,
  FilePlus,
  Files,
  Paperclip,
  BookmarkSimple,
  Tag,
  TagChevron,
  Robot,
  WarningOctagon,
  CalendarX,
  Bathtub,
  Snowflake,
  WifiSlash,
  ToggleLeft,
  ToggleRight,
  Notepad,
  NotePencil,
  TreeStructure,
  CheckSquare,
  FileMagnifyingGlass,
  ShieldCheck,
  Link,
  Palette,
  ListPlus,
  Ruler,
  Play,
  Pause,
  Power,
  SpinnerGap,
  Database,
  HardDrives,
  Backspace,
  FireExtinguisher,
  Key,
  Plug,
  ShieldWarning,
  Recycle,
  Bug,
  Wind,
  type Icon as PhosphorIcon,
} from '@phosphor-icons/react';

// Map from app icon names → Phosphor icon components
export const PHOSPHOR_MAP: Record<string, PhosphorIcon> = {
  // Navigation & Layout
  LayoutDashboard: SquaresFour,
  Menu: List,
  X: X,
  ChevronRight: CaretRight,
  ChevronDown: CaretDown,
  ChevronUp: CaretUp,
  ChevronLeft: CaretLeft,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  ArrowUpRight: ArrowUpRight,
  ExternalLink: ArrowSquareOut,
  Home: House,
  MoreHorizontal: DotsThreeOutline,
  MoreVertical: DotsThreeOutlineVertical,
  LayoutList: Rows,
  LayoutGrid: GridFour,
  MenuBook: BookOpen,
  RestaurantMenu: ForkKnife,

  // Actions
  Plus: Plus,
  Minus: Minus,
  Pencil: PencilSimple,
  Trash2: Trash,
  Save: FloppyDisk,
  Copy: Copy,
  Search: MagnifyingGlass,
  Filter: Funnel,
  Sort: ArrowsDownUp,
  RefreshCw: ArrowsClockwise,
  Download: DownloadSimple,
  Upload: UploadSimple,
  Send: PaperPlaneTilt,
  Link2: LinkSimple,
  Archive: Archive,

  // Status & Feedback
  Check: Check,
  CheckCircle2: CheckCircle,
  AlertTriangle: Warning,
  AlertCircle: WarningCircle,
  XCircle: XCircle,
  Info: Info,
  Eye: Eye,
  EyeOff: EyeSlash,

  // Business & Finance
  DollarSign: CurrencyDollar,
  Wallet: Wallet,
  Landmark: Bank,
  CreditCard: CreditCard,
  Receipt: Receipt,
  ArrowUpCircle: ArrowCircleUp,
  ArrowDownCircle: ArrowCircleDown,
  ArrowLeftRight: ArrowsLeftRight,
  ArrowRightLeft: ArrowsLeftRight,
  TrendingUp: TrendUp,
  TrendingDown: TrendDown,
  PieChart: ChartPie,
  Percent: Percent,
  Coins: Coins,
  ShoppingCart: ShoppingCart,
  ShoppingBag: ShoppingBag,
  ShoppingBasket: Basket,

  // People & Communication
  User: User,
  UserPlus: UserPlus,
  Users: Users,
  Handshake: Handshake,
  UserSearch: UserList,
  UserCheck: UserCheck,
  MessageCircle: ChatCircle,
  MessageSquare: ChatTeardropDots,
  Mail: Envelope,
  Bell: Bell,
  BellRing: BellRinging,
  Phone: Phone,
  Send2: PaperPlaneTilt,

  // Organization
  Package: Package,
  PackageX: Package,
  PackageCheck: Package,
  Clipboard: Clipboard,
  ClipboardCheck: ClipboardText,
  ClipboardList: ListChecks,
  Folder: Folder,
  FileText: FileText,
  StickyNote: Note,
  ListChecks: ListChecks,

  // Settings & System
  Settings: Gear,
  Settings2: SlidersHorizontal,
  Shield: Shield,
  Lock: Lock,
  Unlock: LockOpen,
  LogOut: SignOut,
  Building2: Buildings,
  Monitor: Monitor,
  Globe: Globe,
  Hash: Hash,
  Scale: Scales,

  // Content & Media
  Image: ImageSquare,
  Camera: Camera,
  BookOpen: BookOpenText,
  Lightbulb: Lightbulb,
  Sparkles: Sparkle,
  Brain: Brain,

  // Time & Calendar
  CalendarDays: CalendarDots,
  Calendar: CalendarBlank,
  Clock: Clock,
  History: ClockCounterClockwise,

  // Food & Industry
  ChefHat: CookingPot,
  Utensils: ForkKnife,
  Soup: CookingPot,
  UtensilsCrossed: ForkKnife,

  // Rewards & Achievements
  Gift: Gift,
  Star: Star,
  Trophy: Trophy,
  Crown: Crown,
  Gem: Diamond,
  Medal: Medal,
  Award: Certificate,
  WorkspacePremium: Certificate,
  PartyPopper: Confetti,
  FlaskConical: Flask,
  Calculator: Calculator,

  // Misc
  Sun: Sun,
  Moon: Moon,
  QrCode: QrCode,
  Megaphone: Megaphone,
  Target: Crosshair,
  Grip: DotsSixVertical,
  GripVertical: DotsSixVertical,

  // Transport & Vehicles
  Car: Car,
  Truck: Truck,
  Bus: Bus,
  Fuel: GasPump,
  Plane: AirplaneTilt,

  // Finance categories
  Banknote: Money,
  BadgeDollarSign: CurrencyCircleDollar,
  PiggyBank: PiggyBank,
  HandCoins: Coins,
  CircleDollarSign: CurrencyCircleDollar,
  BarChart3: ChartBar,
  BarChart: ChartBar,
  LineChart: ChartLine,
  Activity: Activity,
  Repeat: Repeat,
  FileSignature: FileSignature,

  // Building & Places
  Briefcase: Briefcase,
  Building: Building,
  Store: Storefront,
  Hospital: FirstAidKit,
  GraduationCap: GraduationCap,

  // Home & Living
  House: House,
  Armchair: Armchair,
  Sofa: Armchair,
  Droplets: Drop,
  Zap: Lightning,
  Wifi: Wifi,
  Wrench: Wrench,
  Hammer: Hammer,
  Paintbrush: PaintBrush,
  Scissors: Scissors,

  // Health & Body
  Heart: Heart,
  HeartPulse: Heartbeat,
  Pill: Pill,
  Stethoscope: Stethoscope,
  Dumbbell: Barbell,

  // Entertainment
  Music: MusicNote,
  Film: FilmSlate,
  Gamepad2: GameController,
  Dices: Dice,
  Ticket: Ticket,
  Coffee: Coffee,
  Wine: Wine,
  Beer: BeerStein,
  Pizza: Pizza,
  Apple: Apple,
  Croissant: Bread,
  Beef: Hamburger,
  Drumstick: Hamburger,
  Sandwich: Hamburger,
  Salad: Leaf,
  Milk: Drop,
  Wheat: Leaf,
  Candy: Bread,
  Egg: Egg,
  SprayCan: SprayBottle,

  // Tech
  Smartphone: DeviceMobile,
  Shirt: TShirt,
  Flame: Fire,
  Laptop: Laptop,
  Tv: Television,
  Headphones: Headphones,
  Printer: Printer,

  // Nature
  TreePine: Tree,
  Flower2: Flower,
  Dog: PawPrint,
  Cat: PawPrint,
  Leaf: Leaf,

  // Documents
  FileCheck: CheckSquare,
  FilePlus: FilePlus,
  Files: Files,
  Paperclip: Paperclip,
  Bookmark: BookmarkSimple,
  Tag: Tag,
  Tags: TagChevron,

  // Additional
  Bot: Robot,
  Vault: Lock,
  CircleAlert: WarningOctagon,
  CalendarRange: CalendarX,
  CalendarIcon2: CalendarBlank,
  Bath: Bathtub,
  Snowflake: Snowflake,
  WifiOff: WifiSlash,
  ToggleLeft: ToggleLeft,
  ToggleRight: ToggleRight,
  Edit2: PencilSimple,
  PenLine: Notepad,
  PenSquare: NotePencil,
  FolderTree: TreeStructure,
  CheckSquare: CheckSquare,
  FileSearch: FileMagnifyingGlass,
  ShieldCheck: ShieldCheck,
  Link: Link,
  CheckCircle: CheckCircle,
  Palette: Palette,
  ListPlus: ListPlus,
  Ruler: Ruler,
  FileImage: ImageSquare,
  ImageIcon: ImageSquare,
  Play: Play,
  Pause: Pause,
  Power: Power,
  Loader2: SpinnerGap,
  Progress_activity: SpinnerGap,
  Database: Database,
  HardDrive: HardDrives,
  Delete: Backspace,

  // Compliance / Safety
  FireExtinguisher: FireExtinguisher,
  KeyRound: Key,
  Key: Key,
  Plug: Plug,
  Plug2: Plug,
  ShieldAlert: ShieldWarning,
  Recycle: Recycle,
  Bug: Bug,
  Wind: Wind,

  // Material Symbol pass-through (now Phosphor)
  EmojiEvents: Trophy,
  Storefront: Storefront,
  Casino: Dice,
};
